@startuml
actor request
participant 缓存层 as cache
participant 击穿拦截    as breakdown
database 持久层    as db

request -> cache
activate cache
alt 存在
    cache --> request
else 不存在
    cache -> breakdown
    alt
    breakdown -> db
    db --> cache
    cache --> request
end
@enduml